#Andrew O. Hall
#Squirrels in Central Park

# Installing a package to pull from GitHub
install.packages("remotes")

# Code to pull a data set from GitHub
remotes::install_github("mine-cetinkaya-rundel/nycsquirrels18")

library(nycsquirrels18)
library(tidyverse)

dim(squirrels)

squirrels %>% head()
squirrels %>% tail()

#plot 1
ggplot(squirrels, aes(x = long, y = lat)) +
  geom_point(alpha = 0.2)


#plot 2

squirrels <- squirrels %>%
  separate(hectare, into = c("NS", "EW"), sep = 2, remove = FALSE) %>%
  mutate(where = if_else(NS %in% c("01", "42") | EW %in% c("A", "I"), "perimeter", "inside"))
ggplot(squirrels, aes(x = long, y = lat, color = where)) +
  geom_point(alpha = 0.2)


#plot 3
hectare_counts <- squirrels %>%
  group_by(hectare) %>%
  summarise(n = n())
hectare_centroids <- squirrels %>%
  group_by(hectare) %>%
  summarise(
    centroid_x = mean(long),
    centroid_y = mean(lat)
  )
squirrels %>%
  left_join(hectare_counts, by = "hectare") %>%
  left_join(hectare_centroids, by = "hectare") %>%
  ggplot(aes(x = centroid_x, y = centroid_y, color = n)) +
  geom_hex()

# Attention: Squirrel Starring at ME!

squirrels %>%
  filter(str_detect(other_interactions, "star")) %>%
  select(shift, age, other_interactions)
